skillMetadata:
  sections:
    - name: Sonos TTS server domain
      fields:
        - name: domain
          type: text
          label: Domain name
          value: ""
        - name: port
          type: number
          value: 3002
